In [1]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [2]:
#load the model,encoders and the scaler
model=load_model('model.h5')

with open('label_encoder_gender.pkl','rb') as file:
    label_encoder_gender=pickle.load(file)

with open('onehot_encoder_geography.pkl','rb') as file:
    onehot_encoder_geo=pickle.load(file)

with open('scaler.pkl','rb') as file:
    scaler=pickle.load(file)

In [3]:
# Example input data
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [7]:
#Geography encoding
geo_encoded=onehot_encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=onehot_encoder_geo.get_feature_names_out())
geo_encoded_df

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [ ]:
input_df=pd.DataFrame([input_data]) # why do we use [] -> to tell taht we are passing lsit of values
input_df

   CreditScore Geography Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          600    France   Male  ...          1               1            50000

[1 rows x 10 columns]

In [11]:
#encode gender
input_df['Gender']=label_encoder_gender.transform(input_df['Gender'])
input_df

   CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          600    France       1  ...          1               1            50000

[1 rows x 10 columns]

In [ ]:
input_df=pd.concat([input_df.drop("Geography",axis=1),geo_encoded_df],axis=1) # why to pass the list
input_df

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          600       1  ...                0.0              0.0

[1 rows x 12 columns]

In [14]:
#scaling the test data
input_df=scaler.transform(input_df)
input_df

array([[-0.52285383,  0.92087016,  0.10660465, -0.70071777, -0.25837365,
         0.80018215,  0.6464804 ,  0.96559161, -0.85938744,  1.00551521,
        -0.58100686, -0.57792762]])

In [15]:
prediction=model.predict(input_df)
prediction

1/1 [==============================] - 0s 188ms/step

array([[0.05041373]], dtype=float32)

In [17]:
prediction_prob=prediction[0][0]
print(prediction_prob)

0.050413728